### ISSUE TITLE
In the first question, how to get the master and node machines to bootstrap a Kubernetes cluster?

### ISSUE THREAD

**Issue by himadriganguly** [jpseara/cka-practice-environment-answers#1]
For the first question "Bootstrap a Kubernetes v1.10 cluster using kubeadm" how we will get the master and the node machines.

**Comment by jpseara** [comment]
You can't do that using Minikube. You can spin 3 VMs in your laptop and do that. If you're using online academies like Linux Academy, they will give you a Lab for that on the fly.
